---
abstract: 'Thread-safe queues'
author:
  - 'Jerry D. Hedden <jdhedden AT cpan DOT org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Thread-Queue
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: '1.1'
  Test::More: '0.5'
  Thread::Semaphore: '0'
  threads::shared: '1.21'
version: '3.03'
